name: FantasyWar
version: '${project.version}'
main: kyubii.de.fantasywar.FantasyWar
author: Kyubiilikesweat
api-version: '1.20'
softdepend: [PlacerholderAPI]
commands:
  Sign:
    permission: itemsign.use
  Broadcast:
    aliases: bc
    permission: broadcast.use
  Chatclear:
    aliases: cc
    permission: chatclear.use
  Kopf:
    aliases: [skull, head]
    permission: kopf.use
  Fantasywarp:
    aliases: fw
  Createfantasywarp:
    aliases: createfw
  Deletefantasywarp:
    aliases: deletefw
  Fantasywarpinfo:
    aliases: fwinfo
    permission: fantasywarp.bypass
  Werbung:
  Quest:

